export const routes = {
  home: "/",
  contact: "/contact",
  advertServices: "/advertservice",
  dashboard: "/dashboard",
  continents: "/continents",
  countries: "/continent",
  properties: "/properties",
  property: "/property",
  upload: "/upload",
  lisitingStat: "/lisitingstats",
  lisitingManager: "/lisitingManager",
  tracklisiting: "/tracklisiting",
  dashboardProperties: "/dashboardproperties",
  profile: "/profile",
  settings: "/settings",
};
